spring.datasource.url=jdbc:mysql://localhost:3306/citizen_ai
spring.datasource.username=root
spring.datasource.password=Vaishnavi@74
gemini.api.key=AQ.Ab8RN6I46tjLXsH0O31YmzLlDaCAUBX4Nw4WziCxjgOHrQPgzA

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true